### ISSUE TITLE
Translation of the `debugging` section in `advanced/metaprogramming`

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#1019]
The original PR can be found [here](https://github.com/doomspork/elixir-school/pull/489).

## Translation
- [x] en #489
- [ ] bg /cc @merkata
- [ ] cn /cc @cizixs
- [x] de /cc @Lechindianer #781
- [ ] es /cc @aleandros / @jonahoffline / @eze1981
- [ ] fr /cc @julienXX
- [x] gr /cc @gemantzu #629
- [ ] id /cc @rezaprima
- [ ] it /cc @lucidstack  / @sformisano
- [x] jp /cc @3100 #507
- [x] ko /cc @devleoper #690
- [ ] my /cc @alkaha
- [ ] no  /cc @Devalo
- [ ] pl /cc @Koziolek 
- [ ] pt /cc @pragmaticivan
- [ ] ru /cc @nscyclone @brain-geek
- [ ] sk /cc @michalvalasek
- [ ] tr /cc @hasanozgan 
- [ ] uk /cc @brain-geek 
- [x] vi /cc @kiennt #918
