### ISSUE TITLE
Suggestion: Explain how functions are named early.

### ISSUE THREAD

**Issue by scouten** [elixirschool/elixirschool#583]
In http://elixirschool.com/lessons/basics/collections/, which is early in the process, you start referring to functions by their arity (i.e. `++/2` when talking about List Concatenation). As a newbie to the language, that syntax is completely unfamiliar (except that I have read a couple of other introductions to the language). IMHO it would help to work in a reference to that syntax early on (or at least mention that you'll get to it later).
## Translation

Translation progress:
- [x] en #599
- [x]  ru /cc @brain-geek / @nscyclone #737
- [x]  ko /cc @devleoper
- [x]  jp /cc @hinamiyagk @3100 #735
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek #849
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [x]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by doomspork** [comment]
Thank you @scouten, I think this is  _great_ suggestion!  Would you be interested in taking a shot at adding this?

**Comment by scouten** [comment]
@doomspork: Yes, I'll take a stab at that. Might be a couple of days before I can get to it.

**Comment by scouten** [comment]
Turns out I had some time today. See PR #599.

**Comment by nscyclone** [comment]
Shouldn't we update this issue with a translations task list?
The English updates were merged back in August, the [Japanese translation is pending](https://github.com/doomspork/elixir-school/pull/735).

**Comment by doomspork** [comment]
Yes @nscyclone, we should

**Comment by devleoper** [comment]
In Korean translation, PRs by @marocchino have already merged.
