### ISSUE TITLE
Update for 1.4 Enum functionalities/deprecations

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#701]
PR #696 updated the Enumerable section to clarify the new functionalities of `min`/`max` now having an arity 2 version, the deprecation of `uniq/1`, and the addition of `map_every/3`.
# NOTE

**As elixir 1.4 is not yet released, please submit translation PR's to point at `improvement/elixir-1.4`**
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @brain-geek / @nscyclone #708 
- [x]  ko /cc @devleoper #942
- [ ]  jp /cc @3100
- [x]  no /cc @therobinsj #713 
- [x]  pl /cc @Koziolek #715 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by doomspork** [comment]
Thank you @ybur-yug!
