### ISSUE TITLE
Update the `specifics/ets` lesson

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#785]
PR #782 fixed a small shortcoming. The existing translations have to be checked whether they are affected by it.
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @nscyclone #786
- [x]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [x]  pl /cc @Koziolek #847 
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  id /cc @rezaprima 
- [x]  gr /cc @gemantzu #795

**Comment by gemantzu** [comment]
#795 for greek language
