### ISSUE TITLE
Translation of GenStage Lesson

### ISSUE THREAD

**Issue by Koziolek** [elixirschool/elixirschool#856]
The new [GenStage](https://github.com/doomspork/elixir-school/commit/73f465be84608947588bb024868fed0677304b38) lesson is ready.

PR #770 was the origin.

## Translation

Translation progress:
- [x] en - #710  
- [x]  ru - /cc @brain-geek / @nscyclone #845 
- [ ]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj 
- [x]  pl /cc @Koziolek #902 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima
- [x]  gr /cc @gemantzu #821

**Comment by gemantzu** [comment]
#821 for greek, the system had an issue so it might be a later commit than this.
