### ISSUE TITLE
Translation of Poolboy Lesson

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#884]
The new [Poolboy](https://github.com/doomspork/elixir-school/blob/master/lessons/libraries/poolboy.md) lesson is ready.

## Translation

Translation progress:
- [x] en - #833  
- [x]  ru - /cc @nscyclone #892 
- [x]  ko /cc @devleoper #838
- [ ]  jp /cc @3100
- [ ]  no /cc @Devalo
- [ ]  pl /cc @Koziolek 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [x]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima
- [x]  gr /cc @gemantzu #858

**Comment by pragmaticivan** [comment]
pt-BR https://github.com/doomspork/elixir-school/pull/913
