### ISSUE TITLE
Translation of new IEx Helpers lesson

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#922]
Another new lesson, this one on IEx helpers courtesy of @ybur-yug!  Original PR here: https://github.com/doomspork/elixir-school/pull/824

## Translation

Translation progress:
- [x] en #824
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  fr /cc @julienXX
- [x]  gr /cc @gemantzu #945
- [ ]  id /cc @rezaprima
- [ ]  it /cc @sformisano
- [x]  ja /cc @3100 #1248
- [x]  ko /cc @devleoper #1070
- [ ]  my /cc @alkaha
- [x]  no /cc @Devalo
- [x]  pl /cc @Koziolek #932 
- [x]  pt /cc @pragmaticivan
- [ ]  ru - /cc @nscyclone
- [x]  sk /cc @michalvalasek
- [ ]  vi /cc @joneslee85

**Comment by 3tarazona** [comment]
Hi, I would like to help with Spanish translations! Let me know if you need my help in any document.

**Comment by nscyclone** [comment]
Hi, @3tarazona!
AFAIK the Spanish translations are not started yet, so you probably would be interesting in beginning it from scratch.
We have a [small section](https://github.com/doomspork/elixir-school/blob/master/README.md#translating) about translations in our README that might be helpful. There are also some [common rules](https://github.com/doomspork/elixir-school/blob/master/CONTRIBUTING.md) for contributions.
If you will have any questions after reading these, feel free to ask here. We are glad to help.
Thanks in advance!

**Comment by brain-geek** [comment]
FYI @nscyclone I would like to take this one for translation also.

**Comment by gemantzu** [comment]
#945 greek

**Comment by stfnsr** [comment]
I'd like to get started with the german translation of this (as this seems to be the only missing section from the basics)

**Comment by iguchi1124** [comment]
Hi! I'd like to try japanese translation of this doc:smile:
