### ISSUE TITLE
Protocol Lesson Translation

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#956]
Original PR Here #825.

This adds a lesson on Protocols. It is not yet merged but final feedback has been incorporated.

## Translation
- [x] en #825
- [ ] bg
- [ ] bn
- [ ] cn /cc @cizixs
- [ ] de
- [ ] es /cc @aleandros / @jonahoffline / @eze1981
- [ ] fr /cc @julienXX
- [x] gr /cc @gemantzu #958 
- [ ] id /cc @rezaprima
- [ ] it /cc @sformisano
- [ ] jp /cc @3100
- [ ] ko /cc @devleoper 
- [ ] my /cc @alkaha
- [ ] no  /cc @Devalo
- [ ] pl /cc @Koziolek
- [x] pt /cc @pragmaticivan #977 
- [x] ru /cc @nscyclone @brain-geek #978
- [ ] sk /cc @michalvalasek
- [ ] tr /cc @hasanozgan 
- [ ] uk /cc @brain-geek 
- [ ] vi /cc @joneslee85

**Comment by brain-geek** [comment]
I'll take Russian translation. @nscyclone , do you agree?

**Comment by nscyclone** [comment]
@brain-geek, I wanted to take it too but I don't mind if you'll take it.

**Comment by gemantzu** [comment]
#958 for greek

**Comment by pragmaticivan** [comment]
https://github.com/pragmaticivan/elixir-school/commit/a8543d622f6824b02097dc8147d95f50863ac170
