### ISSUE TITLE
[BN] Translation task list

### ISSUE THREAD

**Issue by masnun** [elixirschool/elixirschool#970]
## Get Involved!

We are seeking **Bengali** translators for this project. If you would like to get involved with translating a lesson please fork the project and start translating.

- **Set up**
  - [x] _config.yml (@masnun)
  - [x] index.md (@prio101)
- **Basics**
  - [x] basics.md (@masnun)
  - [x] collections.md (@code-shoily)
  - [x] enum.md (@prio101)
  - [x] pattern-matching.md (@code-shoily)
  - [x] control-structures.md (@masnun)
  - [x] functions.md (@code-shoily)
  - [x] pipe-operator.md (@code-shoily)
  - [x] modules.md (@code-shoily)
  - [x] mix.md (@code-shoily)
  - [x] sigils.md (@code-shoily)
  - [x] documentation.md (@code-shoily)
  - [x] testing.md (@prio101)
  - [x] comprehensions.md (@code-shoily)
  - [x] strings.md (@code-shoily)
  - [x] mix-tasks.md (@prio101)
  - [x] iex-helpers.md (@code-shoily)
- **Advanced**
  - [ ] erlang.md
  - [ ] error-handling.md
  - [ ] escripts.md
  - [ ] concurrency.md
  - [ ] otp-concurrency.md
  - [ ] otp-supervisors.md
  - [ ] metaprogramming.md
  - [ ] umbrella-projects.md
  - [ ] typespecs.md
  - [ ] behaviours.md
  - [ ] gen-stage.md
  - [ ] protocols.md
- **Specifics**
  - [ ] plug.md
  - [ ] ecto.md
  - [ ] eex.md
  - [ ] ets.md
  - [ ] mnesia.md
  - [ ] debugging.md
- **Libraries**
  - [ ] guardian.md
  - [ ] poolboy.md

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by masnun** [comment]
Please comment when you take new chapters or complete. I will update the list. 

cc: @prio101 and @code-shoily

**Comment by prio101** [comment]
Great ...

**Comment by code-shoily** [comment]
I will be working on Sigil and Mix in the next 2 days. Fixed my font issue so hopefully I won't be bothering @masnun with silly typos.

**Comment by masnun** [comment]
I am updating the index. BTW, I won't be bothered at all. I am very happy to help.

**Comment by doomspork** [comment]
Thank you all for making this happen, it's so awesome!  Please let me know if there's anything I can help with 😀

**Comment by prio101** [comment]
@masnun Brother I am done with `Enum` Chapter . Its waiting as a Open Pull request . And I would request you to update the `Enum` chapter and also , Now I am going for the `Pattern Matching` chapter. Thanks in advance .

**Comment by masnun** [comment]
@code-shoily  vaiya, please let me know which ones were merged and which one you're currently working on. I will update the list.

**Comment by masnun** [comment]
@prio101  Please let me know when the `Enum` chapter is merged. I will update the list. 

I have reserved Pattern Matching for you.

**Comment by prio101** [comment]
Thanks @masnun Vaiya

**Comment by masnun** [comment]
Enum is merged. Collection was merged before. Checked them off.

**Comment by code-shoily** [comment]
Please add `Pipe Operator` and `Comprehension` as assigned to me? I'm interested to do those. Will be done with `Sigil` by tomorrow. Sorry for the delay, got busy preparing for my talk :(

**Comment by code-shoily** [comment]
And I have sent pull requests for `Mix` and `Pattern Matching`. Had a discussion with @prio101 and took pattern matching from him.. :/ if you'd be so kind and complement my `Mix` with `Mix Task` as discussed bro?

**Comment by code-shoily** [comment]
And how about filling up all of the lessons under `Basic` in here as Task List? So that we can see the bigger picture @masnun ?

**Comment by prio101** [comment]
@masnun vai.. I am going to work on 'mix task'..

**Comment by masnun** [comment]
Does it look right now? I will pull in all the chapters later today.

**Comment by prio101** [comment]
and also @masnun vai...  assign me the 'testing' chapter.

**Comment by masnun** [comment]
Done

**Comment by code-shoily** [comment]
@masnun `Mix` and `Pattern Matching` are merged, maybe cross them out?

**Comment by nscyclone** [comment]
Done, thanks, @code-shoily!

**Comment by code-shoily** [comment]
@masnun let's do this thing, after finishing up all the lessons on the `Basics` section, let's get back and perfect it by shuffling the chapters away from the contributors, that way we can weed out the typos and have a better quality material that looks and feels more natural and native? 

And after that we party :P and move on to next section? Just a suggestion.

**Comment by masnun** [comment]
Impressive work by @code-shoily  - progressing very very fast! 

Yes, that is an excellent idea. After we are done with the basics, we should *all* go through the chapters individually and polish the work done. 

We could use the `#bangladesh` channel in Elixir slack for discussion.

**Comment by code-shoily** [comment]
This can be an invaluable resource for Bangla speaking Elixir learners, we can also share the links once the basic is updated fully, so that by the time potential learners complete the basic section, we can have the advanced sections ready. By the way, I have sent pull requests for 4 more lessons. Do check? :)

**Comment by masnun** [comment]
Yes, reviewed them all. Thanks for all the good work! Really appreciate it!

**Comment by nscyclone** [comment]
Guys, thanks a lot for your amazing job!
I've recently merged [some of your latest translations](https://github.com/doomspork/elixir-school/pulls?utf8=%E2%9C%93&q=is%3Apr%20merged%3A%3E%3D2017-03-06%20%5BBN%5D%20) and wanted to mark them as done here. But unfortunately this format seems a little unusual for me, so I couldn't finally decide to do it.
We usually separate the lessons in the task lists by sections and sort them to make navigation through it a little easier. Here's an [example](https://github.com/doomspork/elixir-school/issues/220).
What do you think about updating this issue into such a format? Or maybe you have any other suggestion to improve the contributors' "quality of life"?
Feel free to ask me if you need any help.

**Comment by masnun** [comment]
The format makes sense to me. It will need me some time to do that. I will pull all the tasks and order them by section (as seen in the other example). Thanks for pointing out!

**Comment by code-shoily** [comment]
@masnun why don't you just copy the list from the given link straight away, that way you won't need much effort for pulling or sorting as it's done already for you? You can always write an Elixir script to append the check-list code and replace/update the contributor names to match with our existing list if you want to have some fun while at it :P

**Comment by code-shoily** [comment]
Guys, I've sent pull requests for `Mix.Task` and `Control Structure`. If they're merged, we'll be left with only two lessons in the basics section. `Testing` and `Documentation`. @prio101 wanted to do the `Testing` chapter, how's that coming along?

Would you like taking a stab at `Documentation` @masnun ? Anyways, I'll start checking out the already translated chapters and add more niceties and native feel to them if needed. 

And since I am going to use `EEx` heavily for a project at hand, I probably will sneak out of the rulesets and translate that while at it ;-)  

Thanks Guys

**Comment by prio101** [comment]
@code-shoily sorry vai . Going through the Mid-Term Exam . :taco:  

and please check this pull #1007 .

So , It seems someone is going to throw a party ???? :smile:

**Comment by code-shoily** [comment]
@prio101 I throw great parties. All I need is an excuse. On a serious note though, I will finish up the documentation lesson tonight. Not before checking your pull request though. Thanks man!

**Comment by code-shoily** [comment]
Guys, let's congratulate ourselves for the completion of the basics section. From here on things fork two-ways in tendem.

1. We continue contributing to some of the chapters in other sections. Some of them, such as `Protocol`, `Specifications and Types`, `Metaprogramming`, `Error Handling` etc map with language syntax so those could be attempted earlier on so that we get a syntax first approach.
2. We revise our existing translations and beautify the language to make the flow smoother.

I have invited @uroybd to contribute to the second part (at least) since he is a very good writer and has recently taken an interest in the language. And while most of the write-ups under the `Basic` section is good, it still feels a bit more `Directly Translated` and in places could use a more native feel. One merge per lesson could make it a perfect `Bengali` resource for learning `Elixir`. So let's do this?

@masnun probably it's time we updated the task list to match the format @nscyclone gave? Maybe add a version too?

Do tell what you think.

cc: @prio101 @doomspork

**Comment by prio101** [comment]
@code-shoily vai ...Agreed ... so lets make it happen ...

**Comment by uroybd** [comment]
Hello,
I have some proposal on programming Jargons. Jargons, even in their native language can be vague for newbies, let alone a non-native one. But, they are equally complicated (and often misleading) to translate them. So, It would be better if we use footnotes. Consider this line and the bold Jargons in it: "এলিক্সির ইন্টার্নালি Erlang VM (BEAM) ব্যবহার করে যেটা **ডিস্ট্রিবিউটেড**, **ফল্ট টলারেন্ট** এবং **লো ল্যাটেন্সী** সিস্টেম ডেভেলপমেন্ট এ সাফল্যের প্রমান রেখে এসেছে ।" Neither literal translation will make any sense here nor this is self-explanatory for a Bengali reader. We can write brief but adequate notes for them. Jekyll have quite a support for footnotes so technically we are good to go.

**Comment by prio101** [comment]
@uroybd ... going to learn a lot from you ...

**Comment by masnun** [comment]
I don't think we can view markdown source of the issue / comment posted by others. So can't copy that over. 

May be someone with higher privilege copy that source for us? Or may be it's better that one of the maintainers manage the task list?

**Comment by nscyclone** [comment]
One more time I want to thank you all for making this happen! Congratulations on completing the first section!

@masnun I've just updated this task list to make it look like the others. The original one can be found [here](http://pastebin.com/NYPW4Vfr). I might be mistaken somewhere so it would be nice if you could re-check the assignments and their completion.

**Comment by masnun** [comment]
Brilliant, thanks a lot! I will check and fix if there are any issues.

**Comment by code-shoily** [comment]
@uroybd good point. The whole thing is about making the Bengali speaking readers comfortable to it and a footnote will certainly help. (Wait till we get to OTP... there'd be a lot of explaining to do there).

I'd still say we need to (re-)progress structurally in this area. Maybe work in the (re-)editors, the revisionist, and the final-checker, where the editor writes the prose, focusing on language ornamentation, the revisionist focuses on the terminology-abuse part and and spellchecks, the final-checker looks at the end-product by running Jekyll and reads from the perspective of an end-user.

**Comment by code-shoily** [comment]
Just checking up on the translators, anyone with any lesson in mind? Either new or improvement?

cc: @masnun @prio101 @uroybd

**Comment by prio101** [comment]
I am going to work on Erlang Chapter.. from advance section this Friday...

**Comment by nscyclone** [comment]
I accidentally found that [the `Testing` lesson's](http://elixirschool.com/bn/lessons/basics/testing/) title remains untranslated. If I am not mistaken in [the end of the lesson](https://github.com/doomspork/elixir-school/blame/master/bn/lessons/basics/testing.md#L145) there is a word `টেস্ট` that is likely was used as a translation for this term. Is this done on purpose?

**Comment by prio101** [comment]
oh.. sorry..  missed that..

**Comment by code-shoily** [comment]
Okay, I'll be reading the `basics` lesson again and beautify sentences along the way. I think I'll do this in sequential order, so starting with the first chapter. :-)

**Comment by masnun** [comment]
I have been away for a while, I am back. I shall try to contribute in my free time. 

I see some more chapters have been done. I shall update this list accordingly. 

/cc: @prio101 @code-shoily @uroybd

**Comment by code-shoily** [comment]
Welcome back. I myself have been away for awhile. I'll be checking out the new chapters as well. Will see if we can go through some of the advanced ones :)

**Comment by doomspork** [comment]
Welcome back!  Thank you again for your help @masnun & @code-shoily 😀

**Comment by code-shoily** [comment]
I will be contributing with the translations from this weekend. I will start going from the beginning and expanding on some topics with additional definitions (for example, "Low Latency", "Fault Tolerant"), the old translations are more or less one-to-one mapping from English but I intend make it more literature friendly on this pass.

Wow it's been quite a long time since I last translated something here :)
